application: pubmedos
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /javascripts
  static_dir: public/javascripts

- url: /stylesheets
  static_dir: public/stylesheets

- url: /images
  static_dir: public/images

- url: /articles/(\d+)/folders
  script: controllers/articles_folders.py

- url: /(users|articles|folders)
  script: controllers/\1.py

- url: /(|login|logout|register|activate|terms|help|about)
  script: controllers/root.py

- url: /.*
  script: not_found.py
