application: pubmedos
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /javascripts
  static_dir: static/javascripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /articles/(\d+)/folders(/?|/.*)
  script: controllers/articles_folders.py

- url: /(users|articles|folders)(/?|/.*)
  script: controllers/\1.py

- url: /(logout|terms|privacy|help|about)(/?|/.*)
  script: controllers/root.py

- url: /(login|register|activate)(/?|/.*)
  script: controllers/root.py
  secure: always

- url: /.*
  script: not_found.py

