application: pubmedos
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /javascripts
  static_dir: static/javascripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /(login|register|activate)(/?|/.*)
  script: main.py
  secure: always

- url: /admin(/?|.*)
  script: main.py
  login: admin
  secure: always

- url: /.*
  script: main.py

